name: Link Checker
on:
    push:
    workflow_dispatch:
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  linkchecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          args: --accept=200,401,403,429 --exclude-mail **/*.html **/*.md --exclude-file layouts/* --exclude "[\$\{\}]"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}