name: Link Checker
on:
    push:
    workflow_dispatch:
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  linkchecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --accept=200,401,403,429 --exclude-mail content/en --exclude-path layouts/404.html --exclude-path README.md --exclude http://localhost --exclude twitter.com --remap "https://iishiishii.github.io/neurodesk.github.io/ file://${GITHUB_WORKSPACE}/static"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}