name: check broken links

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.112.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: BoundfoxStudios/action-hugo-link-check@v1
        with:
          hugo-content-dir: ./content/en
          hugo-config: ./config.toml

      - name: Codespell
        uses: codespell-project/actions-codespell@v1
    