name: check broken links

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.112.7
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Set baseURL
        run: sed -i "s|https://www.neurodesk.org/|${{ steps.pages.outputs.base_url }}/|g" config.toml

      - uses: BoundfoxStudios/action-hugo-link-check@v1
        with:
          hugo-root: content
          hugo-content-dir: content/en
          hugo-config: config.toml

      - name: Codespell
        uses: codespell-project/actions-codespell@v1
    