name: github pages

on:
  push:
    branches: ["main"]
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.102.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Change baseURL (if fork)
        if: github.repository != 'NeuroDesk/neurodesk.github.io'
        run: sed -i "s|https://www.neurodesk.org/|https://${GITHUB_REPOSITORY}/|g" config.toml

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Install dependencies
        run: | 
          npm install

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Add custom domain
        if: github.repository == 'NeuroDesk/neurodesk.github.io'
        run: cp ./static/CNAME ./public/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

# name: github pages

# on:
#   push:
#     branches:
#       - main  # Set a branch to deploy
#   pull_request:
#   repository_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: recursive  # Fetch Hugo themes (true OR recursive)
#           fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

#       - name: Change baseURL (if fork)
#         if: github.repository != 'NeuroDesk/neurodesk.github.io'
#         run: sed -i "s|https://www.neurodesk.org/|https://${GITHUB_REPOSITORY}/|g" config.toml

#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: '0.94.0'
#           extended: true
          
#       - name: Setup Node
#         uses: actions/setup-node@v2

#       - name: Cache dependencies
#         uses: actions/cache@v1
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
            
#       - run: npm ci
      
#       - name: Build
#         run: hugo --minify

#       - name: Add custom domain
#         if: github.repository == 'NeuroDesk/neurodesk.github.io'
#         run: cp ./static/CNAME ./public/CNAME

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: github.ref == 'refs/heads/hugo-docsy'
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public
